name: Spectralyzer-PR

on:
  pull_request:
    branches:
      - main

env:
  CONFIGURATION: "Release"
  ENVIRONMENT: "Production"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      if: ${{ success() }}
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      if: ${{ success() }}
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install T4 dotnet tool
      if: ${{ success() }}
      run: dotnet tool install --global dotnet-t4

    - name: Restore solution
      if: ${{ success() }}
      run: msbuild Spectralyzer.sln -target:restore -property:Configuration=${{ env.CONFIGURATION }} -property:Environment=${{ env.ENVIRONMENT }}

    - name: Build solution
      if: ${{ success() }}
      run: msbuild Spectralyzer.sln -target:rebuild -property:Configuration=${{ env.CONFIGURATION }} -property:Environment=${{ env.ENVIRONMENT }}

    - name: Run unit tests
      if: ${{ success() }}
      run: dotnet test Spectralyzer.sln